# Generated by Django 3.2.9 on 2021-11-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Avg_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('engine_status', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
