# Generated by Django 3.2.9 on 2021-11-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='Avg_speed',
            new_name='avg_speed',
        ),
    ]
