# Generated by Django 3.2.9 on 2021-11-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_image_vehicle_photo_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='photo_1',
            new_name='photo_main',
        ),
    ]
